/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as ChartRouteImport } from './routes/chart'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedPredictionsRouteImport } from './routes/_authenticated/predictions'
import { Route as AuthenticatedManualRouteImport } from './routes/_authenticated/manual'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedAccountRouteImport } from './routes/_authenticated/account'
import { Route as AuthenticatedBacktestSymbolRouteImport } from './routes/_authenticated/backtest/$symbol'
import { Route as AuthenticatedAnalyzeSymbolRouteImport } from './routes/_authenticated/analyze/$symbol'

const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const ChartRoute = ChartRouteImport.update({
  id: '/chart',
  path: '/chart',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedPredictionsRoute =
  AuthenticatedPredictionsRouteImport.update({
    id: '/predictions',
    path: '/predictions',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedManualRoute = AuthenticatedManualRouteImport.update({
  id: '/manual',
  path: '/manual',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAccountRoute = AuthenticatedAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedBacktestSymbolRoute =
  AuthenticatedBacktestSymbolRouteImport.update({
    id: '/backtest/$symbol',
    path: '/backtest/$symbol',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAnalyzeSymbolRoute =
  AuthenticatedAnalyzeSymbolRouteImport.update({
    id: '/analyze/$symbol',
    path: '/analyze/$symbol',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/chart': typeof ChartRoute
  '/privacy': typeof PrivacyRoute
  '/account': typeof AuthenticatedAccountRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/manual': typeof AuthenticatedManualRoute
  '/predictions': typeof AuthenticatedPredictionsRoute
  '/analyze/$symbol': typeof AuthenticatedAnalyzeSymbolRoute
  '/backtest/$symbol': typeof AuthenticatedBacktestSymbolRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/chart': typeof ChartRoute
  '/privacy': typeof PrivacyRoute
  '/account': typeof AuthenticatedAccountRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/manual': typeof AuthenticatedManualRoute
  '/predictions': typeof AuthenticatedPredictionsRoute
  '/analyze/$symbol': typeof AuthenticatedAnalyzeSymbolRoute
  '/backtest/$symbol': typeof AuthenticatedBacktestSymbolRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/chart': typeof ChartRoute
  '/privacy': typeof PrivacyRoute
  '/_authenticated/account': typeof AuthenticatedAccountRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/manual': typeof AuthenticatedManualRoute
  '/_authenticated/predictions': typeof AuthenticatedPredictionsRoute
  '/_authenticated/analyze/$symbol': typeof AuthenticatedAnalyzeSymbolRoute
  '/_authenticated/backtest/$symbol': typeof AuthenticatedBacktestSymbolRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/chart'
    | '/privacy'
    | '/account'
    | '/dashboard'
    | '/manual'
    | '/predictions'
    | '/analyze/$symbol'
    | '/backtest/$symbol'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/chart'
    | '/privacy'
    | '/account'
    | '/dashboard'
    | '/manual'
    | '/predictions'
    | '/analyze/$symbol'
    | '/backtest/$symbol'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/chart'
    | '/privacy'
    | '/_authenticated/account'
    | '/_authenticated/dashboard'
    | '/_authenticated/manual'
    | '/_authenticated/predictions'
    | '/_authenticated/analyze/$symbol'
    | '/_authenticated/backtest/$symbol'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ChartRoute: typeof ChartRoute
  PrivacyRoute: typeof PrivacyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chart': {
      id: '/chart'
      path: '/chart'
      fullPath: '/chart'
      preLoaderRoute: typeof ChartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/predictions': {
      id: '/_authenticated/predictions'
      path: '/predictions'
      fullPath: '/predictions'
      preLoaderRoute: typeof AuthenticatedPredictionsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/manual': {
      id: '/_authenticated/manual'
      path: '/manual'
      fullPath: '/manual'
      preLoaderRoute: typeof AuthenticatedManualRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/account': {
      id: '/_authenticated/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AuthenticatedAccountRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/backtest/$symbol': {
      id: '/_authenticated/backtest/$symbol'
      path: '/backtest/$symbol'
      fullPath: '/backtest/$symbol'
      preLoaderRoute: typeof AuthenticatedBacktestSymbolRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/analyze/$symbol': {
      id: '/_authenticated/analyze/$symbol'
      path: '/analyze/$symbol'
      fullPath: '/analyze/$symbol'
      preLoaderRoute: typeof AuthenticatedAnalyzeSymbolRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAccountRoute: typeof AuthenticatedAccountRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedManualRoute: typeof AuthenticatedManualRoute
  AuthenticatedPredictionsRoute: typeof AuthenticatedPredictionsRoute
  AuthenticatedAnalyzeSymbolRoute: typeof AuthenticatedAnalyzeSymbolRoute
  AuthenticatedBacktestSymbolRoute: typeof AuthenticatedBacktestSymbolRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAccountRoute: AuthenticatedAccountRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedManualRoute: AuthenticatedManualRoute,
  AuthenticatedPredictionsRoute: AuthenticatedPredictionsRoute,
  AuthenticatedAnalyzeSymbolRoute: AuthenticatedAnalyzeSymbolRoute,
  AuthenticatedBacktestSymbolRoute: AuthenticatedBacktestSymbolRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ChartRoute: ChartRoute,
  PrivacyRoute: PrivacyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
